title: Xiaohui's Homepage
page-top-title: Xiaohui
top-section-bg-text: Whatever you do, do it a hundred percent. 倾尽所能，力求极致
home-subtitle: Xiaohui&ensp;|&ensp;晓辉
copyright-text: '&copy; Xiaohui 2023-2025. All Rights Reserved.'
